### ISSUE TITLE
[Not sure if bug] Advanced/Overlay/Skin empty

### ISSUE THREAD

**Issue by Kukoro** [LaughingHyena279/boston-cream-pie#6]
![image](https://user-images.githubusercontent.com/19671583/83920519-b0126400-a77c-11ea-8bac-3296133cdc2b.png)
![image](https://user-images.githubusercontent.com/19671583/83920571-cf10f600-a77c-11ea-8ffd-41574835e2b6.png)
![image](https://user-images.githubusercontent.com/19671583/83920605-dfc16c00-a77c-11ea-9daf-922d123b59dc.png)

**Comment by LaughingHyena279** [comment]
Not a bug, no overlays are included.
