### ISSUE TITLE
DEF_UI - Inventar icons missing

### ISSUE THREAD

**Issue by Kukoro** [LaughingHyena279/boston-cream-pie#7]
![image](https://user-images.githubusercontent.com/19671583/83926530-57e25e80-a78a-11ea-9247-0cfd7401702f.png)

If I'm correct def_UI looks for keywords in the itemname like [Scrap] and I guess those keywords are missing:

![image](https://user-images.githubusercontent.com/19671583/83926623-ab54ac80-a78a-11ea-899f-4139b3580898.png)

**Comment by LaughingHyena279** [comment]
This is intended, at least until I figure out a way to automate assigning icons to items.
